-d C:\Gowin\prj\uart_tester\impl\gwsynthesis\uart_tester.vg
-p GW1N-1-QFN48-5
-pn GW1N-LV1QN48C5/I4
-cst C:\Gowin\prj\uart_tester\src\uart_tester.cst
-cfg C:\Gowin\prj\uart_tester\impl\pnr\device.cfg
-sdc C:\Gowin\prj\uart_tester\src\uart_tester.sdc
-bit
-tr
-ph
-timing
-cst_error
